### ISSUE TITLE
Address new package.json license property guidelines

### ISSUE THREAD

**Issue by kemitchell** [jameswomack/privacy#1]
@othiym23 recently landed a PR of mine to update npm's guidelines on license metadata for packages without licenses and with nonstandard license terms.

The relevant release notes are here: https://github.com/npm/npm/releases/tag/v2.12.0

The updated guidelines are: https://docs.npmjs.com/files/package.json#license

I see that you're using "LicenseRef-LICENSE", but also that there isn't any LICENSE file in the package. If there is a license file you'd like to include, the correct package.json license field value is now `SEE LICENSE IN <filename>`, where `<filename>` is the name of the file holding the license terms.

I'd be happy to send a quick PR to fix package.json, but don't want to presume to know what license terms you want to apply.

Thanks so much for caring about licensing enough to read the previous guidelines and use `LicenseRef-LICENSE`. I know guidelines changes aren't fun, but the new approach is, I think, very much better, and there aren't yet so many packages in the registry using `LicenseRef-LICENSE`, as you are.

Best,
K

**Comment by jameswomack** [comment]
Hi @kemitchell I believe I've updated per your request

**Comment by kemitchell** [comment]
Thanks so much. Again: Sorry for back-and-forth on the guidelines!

**Comment by jameswomack** [comment]
Thank you for notifying me about it.
